version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100;9229:9229"

# packages: []

command:
  build:
    - npm install

  compile:
    - "npm run build"
